Repository Buffes/Ecosystem, pull requests merged in 2020-05, with the labels that each got.

#183 Fix animator updating before entity conversion
  Assets/Prefabs/Animals/Eagle.prefab
  Assets/Prefabs/Animals/Fox.prefab
  Assets/Prefabs/Animals/Rabbit.prefab
  Assets/Prefabs/Animals/Sardine.prefab
  Assets/Scripts/Animation/EntityAnimation.cs
  Assets/Scripts/Attributes/Animal.cs
Labels: bugfix, priority, simple

#187 Fix missing changes after merge
  Assets/Prefabs/Animals/Animal.prefab
  Assets/Prefabs/Animals/Eagle.prefab
  Assets/Prefabs/Animals/Fox.prefab
  Assets/Prefabs/Animals/Rabbit.prefab
  Assets/Prefabs/Animals/Sardine.prefab
  Assets/Prefabs/GameZone.prefab
  Assets/Scenes/Main_scene.unity
Labels: bugfix, priority

#190 Fix main scene settings
  Assets/Editor.meta
  Assets/Prefabs/GameZone.prefab
  Assets/Prefabs/Main Camera.prefab
  Assets/Prefabs/Spawner.prefab
  Assets/Scenes/Main_scene.unity
Labels: priority

#191 Fix animation lag
  Assets/Animations/FoxAnims/Fox Animations.controller
  Assets/Animations/RabbitAnims/Rabbit Anims.controller
Labels: priority, simple

#192 Set default quality to high
  ProjectSettings/QualitySettings.asset
Labels: simple

#194 Changed maximum range for when animals get to drink
  Assets/Scripts/ECS/Physics/GroundCollisionSystem.cs
  Assets/Scripts/StateMachine/ThirstState.cs
Labels: bugfix, simple

#196 Update README.md
  README.md
Labels: simple

#185 Move input values from prefab to animal type
  Assets/Gameplay/AnimalTypes/Eagle.asset
  Assets/Gameplay/AnimalTypes/Fox.asset
  Assets/Gameplay/AnimalTypes/Rabbit.asset
  Assets/Gameplay/AnimalTypes/Sardine.asset
  Assets/Prefabs/Animals/Animal.prefab
  Assets/Prefabs/Animals/Sardine.prefab
  Assets/ScriptableObjects/Gameplay/AnimalType/AnimalType.cs
  Assets/Scripts/ECS/Animal/AgeData.cs
  Assets/Scripts/ECS/Animal/Authoring/AgeAuthoring.cs
  Assets/Scripts/ECS/Animal/Authoring/AnimalTypeAuthoring.cs
  Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
  Assets/Scripts/Spawner/PrefabSpawner.cs
Labels: priority
