Repository Buffes/Ecosystem, pull requests merged in 2020-04, with the labels that each got.

#73 Separate baby DNA and pregnancy duration to allow burst compilation
  Assets/Scripts/ECS/Reproduction/BirthSystem.cs
  Assets/Scripts/ECS/Reproduction/GestationSystem.cs
  Assets/Scripts/ECS/Reproduction/PregnancyData.cs
  Assets/Scripts/ECS/Reproduction/PregnancyData.cs.meta
  Assets/Scripts/ECS/Reproduction/Pregnant.cs
  Assets/Scripts/ECS/Reproduction/Pregnant.cs.meta
  Assets/Scripts/ECS/Reproduction/ReproductionEventSystem.cs
Labels: bugfix, priority

#75 Improved the logic in casual state
  Assets/Scripts/StateMachine/CasualState.cs
Labels: simple

#85 Fix animal hitbox sizes
  Assets/Prefabs/Animals/Chicken.prefab
  Assets/Prefabs/Animals/Lion.prefab
Labels: simple

#92 Add missing add job handle calls
  Assets/Scripts/ECS/Death/DropOnDeathSystem.cs
  Assets/Scripts/ECS/Physics/FreezeRotationSystem.cs
Labels: bugfix, simple

#93 Remove unused entity
  Assets/Scripts/ECS/Hybrid/Interaction.cs
Labels: simple

#94 Fix double death event
  Assets/Scripts/ECS/Animal/AgingSystem.cs
  Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
  Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs
Labels: bugfix, simple

#95 Fix sprint to stop when exhausted
  Assets/Scripts/ECS/Movement/SprintInputSystem.cs
Labels: bugfix, simple

#96 Fix missing entity errors
  Assets/Prefabs/Scenary/Trees/fruitTree.prefab
  Assets/Scripts/Attributes/Animal.cs
  Assets/Scripts/ECS/Grid/Buckets/EntityBucketSystem.cs
  Assets/Scripts/ECS/Hybrid/Interaction.cs
  Assets/Scripts/ECS/Hybrid/Sensors.cs
Labels: bugfix

#97 Changed the namespace reference name
  Assets/Scripts/ECS/Debugging/VisionDebuggingSystem.cs
Labels: bugfix, simple

#102 Fix gestation duration time unit
  Assets/Scripts/ECS/Reproduction/GestationSystem.cs
Labels: simple

#98 Random sex setting
  Assets/Prefabs/Animals/Animal.prefab
  Assets/Scripts/ECS/Animal/Authoring/SexAuthoring.cs
  Assets/Scripts/ECS/Animal/Authoring/SexAuthoring.cs.meta
  Assets/Scripts/ECS/Animal/SexData.cs
Labels: simple

#106 gitignore *.csv
  .gitignore
Labels: simple

#110 Remove ref dependency on PhysicsMass
  Assets/Scripts/ECS/Physics/GroundCollisionSystem.cs
Labels: simple

#111 Increase tree size 3x
  Assets/Prefabs/Scenary/Trees/BaseTree.prefab
Labels: simple

#114 Adjust visual debugging values
  Assets/Materials/Debugging/HearingRange.mat
  Assets/Prefabs/Debugging/VisualDebuggingManager.prefab
Labels: simple

#116 Enable vision debugging by default
  Assets/Prefabs/Debugging/VisualDebuggingManager.prefab
Labels: simple

#118 Adjusted names of animal types and food
  Assets/Gameplay/AnimalTypes/Chicken.asset
  Assets/Gameplay/AnimalTypes/Chicken.asset.meta
  Assets/Gameplay/AnimalTypes/Lion.asset
  Assets/Gameplay/AnimalTypes/Lion.asset.meta
  Assets/Gameplay/AnimalTypes/Sardine.asset
  Assets/Gameplay/AnimalTypes/Sardine.asset.meta
  Assets/Gameplay/FoodTypes/Meat/Chicken.asset
  Assets/Gameplay/FoodTypes/Meat/Chicken.asset.meta
  Assets/Gameplay/FoodTypes/Meat/Lion.asset
  Assets/Gameplay/FoodTypes/Meat/Lion.asset.meta
  Assets/Prefabs/Food/ChickenMeat.prefab
  Assets/Prefabs/Food/ChickenMeat.prefab.meta
  Assets/Prefabs/Food/LionMeat.prefab
  Assets/Prefabs/Food/LionMeat.prefab.meta
Labels: simple

#122 Pregnant animals get constant sexual urge
  Assets/Scripts/ECS/Animal/Needs/SexualUrgesSystem.cs
Labels: simple

#123 Status bars billboard
  Assets/Scripts/ECS/Debugging/StatusBarDebuggingSystem.cs
Labels: simple

#124 Enable scenery
  Assets/Scenes/Main_scene.unity
Labels: simple

#130 Fix build error
  Assets/Scripts/ECS/Animal/AnimalPrefab.cs
  Assets/Scripts/ECS/Animal/Authoring/AnimalTypeAuthoring.cs
  Assets/Scripts/ECS/Reproduction/BirthSystem.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: bugfix, priority, simple

#125 Update Animal.prefab
  Assets/Prefabs/Animals/Animal.prefab
Labels: simple

#132 Fix prefab type error
  Assets/Gameplay/AnimalTypes/Chicken.asset
  Assets/Gameplay/AnimalTypes/Eagle.asset
  Assets/Gameplay/AnimalTypes/Lion.asset
  Assets/Gameplay/AnimalTypes/Sardine.asset
  Assets/ScriptableObjects/Gameplay/AnimalType.cs
  Assets/Scripts/ECS/Animal/Authoring/AnimalTypeAuthoring.cs
Labels: bugfix, priority, simple

#136 Fix adding data points for empty animal counts
  Assets/Scripts/Graphs/AverageAnimalStats.cs
Labels: bugfix, simple

#135 Change animal stats list to linked list
  Assets/Scripts/Graphs/AnimalStats.cs
Labels: simple

#134 Fix death event order
  Assets/Scripts/ECS/Death/DeathEventSystem.cs
Labels: bugfix, simple

#133 Commit auto-changed code on materials
  Assets/Materials/Grass/Grass_Green_01.mat
  Assets/Materials/Seaweed/Leave_Green_01.mat
Labels: simple

#131 Update flee state
  Assets/Scripts/Attributes/Animal.cs
  Assets/Scripts/ECS/Targeting/FindSystems/FindFleeTargetSystem.cs
  Assets/Scripts/StateMachine/FleeState.cs
Labels: simple

#144 Fix food choice
  Assets/Gameplay/AnimalTypes/Lion.asset
Labels: simple

#146 Added Lifespan to food
  Assets/Gameplay/AnimalTypes/Eagle.asset
  Assets/Prefabs/Food/Food.prefab
Labels: simple

#148 Update PregnancyVisualSystem.cs
  Assets/Scripts/ECS/Reproduction/PregnancyVisualSystem.cs
Labels: simple

#145 Removed poolManager
  Assets/Scripts/ECS/Pool.meta
  Assets/Scripts/ECS/Pool/PoolManager.cs
  Assets/Scripts/ECS/Pool/PoolManager.cs.meta
Labels: simple

#152 FrameCounter moved out of Main Camera
  Assets/Prefabs/Debugging/FramerateCounter.prefab
  Assets/Scenes/Main_scene.unity
Labels: simple

#160 Fix maturing food
  Assets/Scripts/ECS/Growth/MaturingSystem.cs
Labels: simple

#161 Fixed missing food types
  Assets/Gameplay/AnimalTypes/Eagle.asset
  Assets/Gameplay/AnimalTypes/Sardine.asset
  Assets/Prefabs/Animals/Chicken.prefab
  Assets/Prefabs/Food/Seaweed.prefab
Labels: simple

#165 Fix FPSCounter SerializeField warnings
  Assets/Scripts/Debugging/FPSCounter.cs
Labels: simple

#166 Add updated FPS counter to the scene
  Assets/Scenes/Main_scene.unity
Labels: simple

#164 Fix simulation settings sending error messages randomly
  Assets/ScriptableObjects/Console/Commands/InitialPopulationCommand.cs
  Assets/ScriptableObjects/Console/Commands/SpawnCommand.cs
  Assets/ScriptableObjects/Gameplay/SimulationSettings.cs
  Assets/Scripts/Spawner/PrefabSpawner.cs
Labels: simple

#170 Fix spawn command ignore case
  Assets/ScriptableObjects/Console/Commands/SpawnCommand.cs
Labels: simple
