Repository Buffes/Ecosystem, pull requests merged in 2020-03, with the labels that each got.

#32 Hunger thirst systems
  Assets/Scripts/ECS/Animal/Needs.meta
  Assets/Scripts/ECS/Animal/Needs/HungerData.cs
  Assets/Scripts/ECS/Animal/Needs/HungerData.cs.meta
  Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
  Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs.meta
  Assets/Scripts/ECS/Animal/Needs/ThirstData.cs
  Assets/Scripts/ECS/Animal/Needs/ThirstData.cs.meta
  Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs
  Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs.meta
  Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
  Assets/Scripts/ECS/Hybrid/NeedsStatus.cs.meta
Labels: bug

#34 Fix burst error
  Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
  Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs
Labels: good first issue, priority

#38 Mate state
  Assets/Scripts/Attributes/Animal.cs
  Assets/Scripts/StateMachine/HungerState.cs
  Assets/Scripts/StateMachine/MateState.cs
Labels: duplicate

#41 Fix missing FoundMate method
  Assets/Scripts/ECS/Hybrid/Sensors.cs
Labels: good first issue, priority

#35 Destroy gameobject on death
  Assets/Scripts/ECS/Animal/Authoring/AnimalTypeAuthoring.cs
  Assets/Scripts/ECS/Animal/Needs/HungerSystem.cs
  Assets/Scripts/ECS/Animal/Needs/ThirstSystem.cs
  Assets/Scripts/ECS/Death.meta
  Assets/Scripts/ECS/Death/DeathEvent.cs
  Assets/Scripts/ECS/Death/DeathEvent.cs.meta
  Assets/Scripts/ECS/Death/DeathEventSystem.cs
  Assets/Scripts/ECS/Death/DeathEventSystem.cs.meta
  Assets/Scripts/ECS/Death/DestroyOnDeath.cs
  Assets/Scripts/ECS/Death/DestroyOnDeath.cs.meta
  Assets/Scripts/ECS/Death/DestroyOnDeathSystem.cs
  Assets/Scripts/ECS/Death/DestroyOnDeathSystem.cs.meta
  Assets/Scripts/ECS/Death/DropOnDeath.cs
  Assets/Scripts/ECS/Death/DropOnDeath.cs.meta
  Assets/Scripts/ECS/Death/DropOnDeathSystem.cs
  Assets/Scripts/ECS/Death/DropOnDeathSystem.cs.meta
  Assets/Scripts/ECS/Events/DeathEvent.cs
  Assets/Scripts/ECS/Hybrid/Interaction.cs
Labels: good first issue

#33 Fix animal instantiation bug
  Assets/Samples/Sample1_HybridECS/Scripts/BasicFollowing.cs
  Assets/Samples/Sample1_HybridECS/Scripts/SyncTransform.cs
  Assets/Scripts/Attributes/Animal.cs
  Assets/Scripts/ECS/Hybrid/HybridBehaviour.cs
  Assets/Scripts/ECS/Hybrid/HybridBehaviour.cs.meta
  Assets/Scripts/ECS/Hybrid/HybridEntity.cs
  Assets/Scripts/ECS/Hybrid/HybridEntity.cs.meta
  Assets/Scripts/ECS/Hybrid/Interaction.cs
  Assets/Scripts/ECS/Hybrid/Movement.cs
  Assets/Scripts/ECS/Hybrid/NeedsStatus.cs
  Assets/Scripts/ECS/Hybrid/Sensors.cs
Labels: priority

#55 Fix animal missing components
  Assets/Samples/Sample1_HybridECS/Prefabs/Animal.prefab
  Assets/Samples/Sample1_HybridECS/Prefabs/Food.prefab
  Assets/Samples/Sample1_HybridECS/Prefabs/Fox.prefab
  Assets/Samples/Sample1_HybridECS/Prefabs/Rabbit.prefab
Labels: priority

#57 Added preprocessor check
  Assets/Scripts/ECS/Debugging/HearingDebuggingSystem.cs
  ProjectSettings/ProjectSettings.asset
Labels: bugfix

#61 Fix missing command buffer completion
  Assets/Scripts/ECS/Death/DeathEventSystem.cs
Labels: bugfix, simple

#59 Change path material shader
  Assets/Materials/Debugging/Path.mat
Labels: bugfix, simple
